---
- name: MySQL DB server installed
  hosts: myVM2
  become: true
  tasks:

  - name: Obtain mysql 7.5 community release
    yum:
      name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
      state: present
  - name: Yum package update
    yum:
      name: '*'
      state: present
  - name: Install mysql-server
    yum:
      name: mysql-server
      state: latest
  - name: MySQL enabled and running
    service:
      name: mysqld
      enabled: true
      state: started
